
workflows:

  simple-workflow:

    name: Native Android

    max_build_duration: 60

    scripts:


emulator -avd emulator > /dev/null 2>&1 &

      - name: Run tests

        script: ./gradlew test

      - name: Build debug apk

        script: ./gradlew assembleDebug

    artifacts:

      - app/build/**/outputs/**/*.apk

    publishing:

      email:

        recipients:

          - rajsuman9939@gmail.com

